# Fastener Library
#
# Generates metric and imperial fasteners: hex nuts, cap nuts, wing nuts,
# washers, hex bolts, socket head cap screws, button head cap screws,
# countersunk screws, set screws, thumbscrews, flat head (slotted) screws,
# Phillips screws, and standoffs.
#
# Each fastener type is its own struct with a `Solid()` method.
# Dimensions are looked up from shared ISO/ASME tables by diameter.
#
# Usage:
#   var F = lib "github.com/firstlayer-xyz/facetlibs/fasteners@main";
#   return F.HexBolt("m8", 30 mm).Solid();
#   return F.HexBolt("1/4-20", 1 in).Solid();

var T = lib "github.com/firstlayer-xyz/facetlibs/threads@main";
var K = lib "github.com/firstlayer-xyz/facetlibs/knurling@main";

# Re-export Knurl constructor so users can create knurl specs without
# importing knurling separately.
Knurl Knurl(Number count, Length depth, Angle pitch_angle) {
    return K.Knurl(count, depth, pitch_angle);
}

# ---------------------------------------------------------------------------
# ISO Metric Dimension Table
#
# Columns:
#   0: diameter     1: hex_af       2: nut_h        3: bolt_head_h
#   4: shcs_head_d  5: shcs_head_h  6: shcs_socket
#   7: bhcs_head_d  8: bhcs_head_h  9: bhcs_socket
#  10: fhcs_head_d 11: fhcs_head_h 12: fhcs_socket
#  13: set_socket
#  14: pan_head_d  15: pan_head_h
#  16: slot_w      17: phillips_w
# ---------------------------------------------------------------------------

var METRIC = [
    [ 2,    4.0,  1.6,  1.4,  3.8,   2.0,   1.5,  3.8,   1.3,   1.3,  3.8,    1.2,   1.3,  0.9,   4.0,   1.3,  0.5,  1.4  ],
    [ 2.5,  5.0,  2.0,  1.7,  4.5,   2.5,   2.0,  4.7,   1.5,   1.5,  4.7,    1.5,   1.5,  1.3,   5.0,   1.7,  0.6,  1.8  ],
    [ 3,    5.5,  2.4,  2.0,  5.5,   3.0,   2.5,  5.7,   1.65,  2.0,  5.54,   1.86,  2.0,  1.5,   6.0,   2.0,  0.8,  2.1  ],
    [ 3.5,  6.0,  2.8,  2.4,  0,     0,     0,    0,     0,     0,    0,       0,     0,    0,     7.0,   2.1,  1.0,  0    ],
    [ 4,    7.0,  3.2,  2.8,  7.0,   4.0,   3.0,  7.6,   2.2,   2.5,  7.53,   2.48,  2.5,  2.0,   8.0,   2.6,  1.0,  2.6  ],
    [ 5,    8.0,  4.7,  3.5,  8.5,   5.0,   4.0,  9.5,   2.75,  3.0,  9.43,   3.1,   3.0,  2.5,  10.0,   3.3,  1.2,  3.3  ],
    [ 6,   10.0,  5.2,  4.0, 10.0,   6.0,   5.0, 10.5,   3.3,   4.0, 11.34,   3.72,  4.0,  3.0,  12.0,   3.9,  1.6,  4.1  ],
    [ 8,   13.0,  6.8,  5.3, 13.0,   8.0,   6.0, 14.0,   4.4,   5.0, 15.24,   4.96,  5.0,  4.0,  16.0,   5.0,  2.0,  5.1  ],
    [10,   16.0,  8.4,  6.4, 16.0,  10.0,   8.0, 17.5,   5.5,   6.0, 19.22,   6.2,   6.0,  5.0,  20.0,   6.0,  2.5,  6.1  ],
    [12,   18.0, 10.8,  7.5, 18.0,  12.0,  10.0, 21.0,   6.6,   8.0, 23.12,   7.44,  8.0,  6.0,  24.0,   7.0,  3.0,  7.1  ],
    [14,   21.0, 12.8,  8.8, 21.0,  14.0,  12.0,  0,     0,     0,   27.0,    7.0,  10.0,  6.0,   0,     0,    0,    0    ],
    [16,   24.0, 14.8, 10.0, 24.0,  16.0,  14.0, 28.0,   8.8,  10.0, 29.01,   8.8,  10.0,  8.0,  30.0,   8.8,  4.0,  0    ],
    [18,   27.0, 15.8, 11.5,  0,     0,     0,    0,     0,     0,   33.0,    8.0,  12.0, 10.0,   0,     0,    0,    0    ],
    [20,   30.0, 18.0, 12.5, 30.0,  20.0,  17.0,  0,     0,     0,   36.05,  10.16, 12.0, 10.0,  36.0,  10.0,  5.0,  0    ],
    [22,   34.0, 19.4, 14.0,  0,     0,     0,    0,     0,     0,   36.0,   13.1,  14.0, 12.0,   0,     0,    0,    0    ],
    [24,   36.0, 21.5, 15.0, 36.0,  24.0,  18.0,  0,     0,     0,   39.0,   14.0,  14.0, 12.0,  44.0,  12.0,  6.0,  0    ],
    [27,   41.0, 23.8, 17.0,  0,     0,     0,    0,     0,     0,    0,      0,     0,    0,     0,     0,    0,    0    ],
    [30,   46.0, 25.6, 19.0, 45.0,  30.0,  22.0,  0,     0,     0,    0,      0,     0,   15.0,   0,     0,    0,    0    ],
    [33,   50.0, 28.7, 21.0,  0,     0,     0,    0,     0,     0,    0,      0,     0,    0,     0,     0,    0,    0    ],
    [36,   55.0, 31.0, 23.0, 54.0,  36.0,  27.0,  0,     0,     0,    0,      0,     0,   18.0,   0,     0,    0,    0    ],
    [39,   60.0, 33.4, 25.0,  0,     0,     0,    0,     0,     0,    0,      0,     0,    0,     0,     0,    0,    0    ],
    [42,   65.0, 34.0, 26.0, 63.0,  42.0,  32.0,  0,     0,     0,    0,      0,     0,   21.0,   0,     0,    0,    0    ],
    [45,   70.0, 36.0, 28.0,  0,     0,     0,    0,     0,     0,    0,      0,     0,    0,     0,     0,    0,    0    ],
    [48,   75.0, 38.0, 30.0, 72.0,  48.0,  36.0,  0,     0,     0,    0,      0,     0,   24.0,   0,     0,    0,    0    ],
    [52,   80.0, 41.0, 33.0,  0,     0,     0,    0,     0,     0,    0,      0,     0,    0,     0,     0,    0,    0    ],
    [56,   85.0, 45.0, 35.0, 84.0,  56.0,  41.0,  0,     0,     0,    0,      0,     0,   28.0,   0,     0,    0,    0    ],
    [60,   90.0, 46.0, 38.0,  0,     0,     0,    0,     0,     0,    0,      0,     0,    0,     0,     0,    0,    0    ],
    [64,   95.0, 51.0, 40.0, 96.0,  64.0,  46.0,  0,     0,     0,    0,      0,     0,   32.0,   0,     0,    0,    0    ],
    [68,  105.0, 54.4, 44.0,  0,     0,     0,    0,     0,     0,    0,      0,     0,    0,     0,     0,    0,    0    ]
];

# ---------------------------------------------------------------------------
# Imperial Dimension Table (ASME B18.2.1, B18.2.2, B18.3, B18.6.3)
#
# Same 18-column layout as METRIC.
# Column 0 = diameter in inches. Columns 1-17 = dimensions in inches.
# DimRow() converts to mm before returning.
# Numbered sizes (#4-#10) have no hex bolts (bolt_head_h=0).
# 7/16-3/4 have no pan head screws.
# ---------------------------------------------------------------------------

var IMPERIAL = [
    #  dia     hex_af nut_h  bolt_h shcs_d shcs_h shcs_s bhcs_d bhcs_h bhcs_s fhcs_d fhcs_h fhcs_s set_s  pan_d  pan_h  slot_w phil_w
    [ 0.112,  1/4,   3/32,  0,     0.183, 0.112, 3/32,  0.225, 0.075, 5/64,  0.225, 0.060, 5/64,  0.050, 0.219, 0.093, 0.039, 0.059 ],
    [ 0.138,  5/16,  7/64,  0,     0.226, 0.138, 7/64,  0.279, 0.093, 7/64,  0.279, 0.073, 7/64,  1/16,  0.262, 0.110, 0.048, 0.071 ],
    [ 0.164,  11/32, 1/8,   0,     0.270, 0.164, 9/64,  0.332, 0.110, 9/64,  0.332, 0.087, 9/64,  5/64,  0.306, 0.128, 0.054, 0.083 ],
    [ 0.190,  3/8,   1/8,   0,     0.312, 0.190, 5/32,  0.385, 0.128, 5/32,  0.385, 0.100, 5/32,  3/32,  0.350, 0.144, 0.060, 0.091 ],
    [ 1/4,    7/16,  7/32,  11/64, 3/8,   1/4,   3/16,  1/2,   5/32,  5/32,  0.452, 0.117, 5/32,  1/8,   0.492, 0.175, 0.075, 0     ],
    [ 5/16,   1/2,   17/64, 7/32,  7/16,  5/16,  1/4,   5/8,   13/64, 3/16,  0.531, 0.151, 3/16,  5/32,  0.615, 0.218, 0.084, 0     ],
    [ 3/8,    9/16,  21/64, 1/4,   9/16,  3/8,   5/16,  3/4,   15/64, 7/32,  0.656, 0.185, 7/32,  3/16,  0.740, 0.261, 0.094, 0     ],
    [ 7/16,   11/16, 3/8,   19/64, 5/8,   7/16,  3/8,   7/8,   17/64, 1/4,   3/4,   0.210, 1/4,   7/32,  0,     0,     0,     0     ],
    [ 1/2,    3/4,   7/16,  11/32, 3/4,   1/2,   3/8,   1,     5/16,  5/16,  0.812, 0.223, 5/16,  1/4,   0,     0,     0,     0     ],
    [ 5/8,    15/16, 35/64, 27/64, 7/8,   5/8,   1/2,   5/4,   3/8,   3/8,   1,     0.283, 3/8,   5/16,  0,     0,     0,     0     ],
    [ 3/4,    9/8,   41/64, 1/2,   9/8,   3/4,   5/8,   3/2,   7/16,  7/16,  9/8,   0.335, 7/16,  3/8,   0,     0,     0,     0     ]
];

# Looks up a row by diameter — tries METRIC first, then IMPERIAL.
# Imperial values are stored in inches; this converts them to mm before returning
# so constructors can use `row[N] * 1 mm` uniformly.
Array DimRow(Length d) {
    var v = Number(d);
    var m = for i [0:<Size(METRIC)] {
        if METRIC[i][0] == v { yield METRIC[i]; };
    };
    if Size(m) > 0 { return m[0]; };
    var vi = v / 25.4;
    var imp = for i [0:<Size(IMPERIAL)] {
        if Abs(IMPERIAL[i][0] - vi) < 0.001 { yield IMPERIAL[i]; };
    };
    assert Size(imp) > 0, "unsupported fastener diameter";
    var row = imp[0];
    return for j [0:<Size(row)] { yield row[j] * 25.4; };
}

# ---------------------------------------------------------------------------
# HexNut — ISO 4032 hex nut
#
# Hex prism body minus internal thread.
# Centered at origin, body from Z=0 upward (+Z).
# ---------------------------------------------------------------------------

struct HexNut {
    Thread thread;
    Length hex_af;
    Length nut_h;
}

# Creates an ISO 4032 hex nut.
HexNut HexNut(String size) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    return HexNut {
        thread: t,
        hex_af: row[1] * 1 mm,
        nut_h: row[2] * 1 mm
    };
}

# Renders the hex nut as a solid.
Solid HexNut.Solid() {
    var cr = self.hex_af / (2 * Cos(30 deg));
    var hex = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * cr, Sin(i * 60 deg) * cr);
    }).Extrude(self.nut_h);
    var internal = self.thread.Inside(self.nut_h);
    return hex - internal;
}

# ---------------------------------------------------------------------------
# CapNut — DIN 1587 cap nut (acorn nut)
#
# Hex base with a domed cap covering the bolt end.
# Centered at origin, body from Z=0 upward (+Z).
# ---------------------------------------------------------------------------

struct CapNut {
    Thread thread;
    Length hex_af;
    Length base_h;
    Length dome_h;
}

# Creates a DIN 1587 cap nut.
CapNut CapNut(String size) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    var af = row[1] * 1 mm;
    return CapNut {
        thread: t,
        hex_af: af,
        base_h: row[2] * 1 mm,
        dome_h: af * 0.45
    };
}

# Renders the cap nut as a solid.
Solid CapNut.Solid() {
    var cr = self.hex_af / (2 * Cos(30 deg));
    var hex = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * cr, Sin(i * 60 deg) * cr);
    }).Extrude(self.base_h);

    # Dome: sphere section clipped to a cylinder above the hex base.
    var dh = self.dome_h;
    var cr_num = cr / (1 mm);
    var dh_num = dh / (1 mm);
    var R_num = (cr_num * cr_num + dh_num * dh_num) / (2 * dh_num);
    var R = R_num * 1 mm;
    var sphere = Sphere(R)
        .Translate(0 mm, 0 mm, self.base_h + dh - R);
    var clip = Cylinder(dh, cr, cr)
        .Translate(0 mm, 0 mm, self.base_h);
    var dome = sphere ^ clip;

    # Internal thread — blind hole through hex base only.
    var internal = self.thread.Inside(self.base_h);

    return (hex + dome) - internal;
}

# ---------------------------------------------------------------------------
# WingNut — DIN 315 wing nut
#
# Central threaded hub with two flat wings.
# Centered at origin, body from Z=0 upward (+Z).
# ---------------------------------------------------------------------------

struct WingNut {
    Thread thread;
    Length major_d;
    Length hub_d;
    Length hub_h;
    Length wing_span;
    Length wing_h;
    Length wing_t;
}

# Creates a DIN 315 wing nut. Dimensions derived proportionally.
WingNut WingNut(String size) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    var af = row[1] * 1 mm;
    var nh = row[2] * 1 mm;
    var md = t.major_diameter;
    return WingNut {
        thread: t,
        major_d: md,
        hub_d: md * 1.7,
        hub_h: nh,
        wing_span: af * 0.9,
        wing_h: nh * 2.5,
        wing_t: md * 0.45
    };
}

# Renders the wing nut as a solid.
Solid WingNut.Solid() {
    var hub = Cylinder(self.hub_h, self.hub_d / 2, self.hub_d / 2);

    var ws = self.wing_span;
    var wh = self.wing_h;
    var wt = self.wing_t;
    var hr = self.hub_d / 2;
    var rect_h = wh - ws / 2;

    # Right wing (+X): rectangle body + semicircular cap
    var rect_r = Cube(ws, wt, rect_h)
        .Translate(hr + ws / 2, 0 mm, rect_h / 2);
    var cap_r = Cylinder(wt, ws / 2, ws / 2)
        .Translate(0 mm, 0 mm, -wt / 2)
        .Rotate(90 deg, 0 deg, 0 deg)
        .Translate(hr + ws / 2, 0 mm, rect_h);
    var clip_r = Cube(ws + 1 mm, wt + 1 mm, ws / 2)
        .Translate(hr + ws / 2, 0 mm, rect_h + ws / 4);
    var wing_r = rect_r + (cap_r ^ clip_r);

    # Left wing (-X): mirror of right wing
    var rect_l = Cube(ws, wt, rect_h)
        .Translate(-(hr + ws / 2), 0 mm, rect_h / 2);
    var cap_l = Cylinder(wt, ws / 2, ws / 2)
        .Translate(0 mm, 0 mm, -wt / 2)
        .Rotate(90 deg, 0 deg, 0 deg)
        .Translate(-(hr + ws / 2), 0 mm, rect_h);
    var clip_l = Cube(ws + 1 mm, wt + 1 mm, ws / 2)
        .Translate(-(hr + ws / 2), 0 mm, rect_h + ws / 4);
    var wing_l = rect_l + (cap_l ^ clip_l);

    var internal = self.thread.Inside(self.hub_h);

    return (hub + wing_r + wing_l) - internal;
}

# ---------------------------------------------------------------------------
# Washer — DIN 125 flat washer
#
# Flat annular ring. Centered at origin, body from Z=0 upward (+Z).
# ---------------------------------------------------------------------------

struct Washer {
    Length bore_d;
    Length outer_d;
    Length thickness;
}

# Creates a DIN 125 flat washer.
Washer Washer(String size) {
    var t = T.New(size);
    var md = t.major_diameter;
    return Washer {
        bore_d: md * 1.05,
        outer_d: md * 2,
        thickness: md * 0.2
    };
}

# Renders the washer as a solid.
Solid Washer.Solid() {
    var outer = Cylinder(self.thickness, self.outer_d / 2, self.outer_d / 2);
    var bore = Cylinder(self.thickness + 1 mm, self.bore_d / 2, self.bore_d / 2)
        .Translate(0 mm, 0 mm, -0.5 mm);
    return outer - bore;
}

# ---------------------------------------------------------------------------
# HexBolt — ISO 4014 hex bolt
#
# Head bottom at Z=0, head extends upward (+Z), shaft extends above head.
# ---------------------------------------------------------------------------

struct HexBolt {
    Thread thread;
    Length hex_af;
    Length head_h;
    Length length;
}

# Creates an ISO 4014 hex bolt with the given shaft length.
HexBolt HexBolt(String size, Length length) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    return HexBolt {
        thread: t,
        hex_af: row[1] * 1 mm,
        head_h: row[3] * 1 mm,
        length: length
    };
}

# Renders the hex bolt as a solid.
Solid HexBolt.Solid() {
    var cr = self.hex_af / (2 * Cos(30 deg));
    var head = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * cr, Sin(i * 60 deg) * cr);
    }).Extrude(self.head_h);
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, self.head_h);
    return head + shaft;
}

# ---------------------------------------------------------------------------
# SocketHeadCapScrew — ISO 4762
#
# Cylindrical head with hex socket recess, threaded shaft above.
# Head at Z=0, shaft extends upward (+Z).
# ---------------------------------------------------------------------------

struct SocketHeadCapScrew {
    Thread thread;
    Length head_d;
    Length head_h;
    Length socket;
    Length length;
}

# Creates an ISO 4762 socket head cap screw.
SocketHeadCapScrew SocketHeadCapScrew(String size, Length length) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    return SocketHeadCapScrew {
        thread: t,
        head_d: row[4] * 1 mm,
        head_h: row[5] * 1 mm,
        socket: row[6] * 1 mm,
        length: length
    };
}

# Renders the socket head cap screw as a solid.
Solid SocketHeadCapScrew.Solid() {
    var hh = self.head_h;
    var head = Cylinder(hh, self.head_d / 2, self.head_d / 2);
    var sock_depth = hh * 0.8;
    var sock_cr = self.socket / (2 * Cos(30 deg));
    var socket = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * sock_cr, Sin(i * 60 deg) * sock_cr);
    }).Extrude(sock_depth + 1 mm)
        .Translate(0 mm, 0 mm, -1 mm);
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, hh);
    return (head - socket) + shaft;
}

# ---------------------------------------------------------------------------
# ButtonHeadCapScrew — ISO 7380
#
# Low-profile dome head with hex socket, threaded shaft above.
# Head at Z=0, shaft extends upward (+Z).
# ---------------------------------------------------------------------------

struct ButtonHeadCapScrew {
    Thread thread;
    Length major_d;
    Length head_d;
    Length head_h;
    Length socket;
    Length length;
}

# Creates an ISO 7380 button head cap screw.
ButtonHeadCapScrew ButtonHeadCapScrew(String size, Length length) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    return ButtonHeadCapScrew {
        thread: t,
        major_d: t.major_diameter,
        head_d: row[7] * 1 mm,
        head_h: row[8] * 1 mm,
        socket: row[9] * 1 mm,
        length: length
    };
}

# Renders the button head cap screw as a solid.
Solid ButtonHeadCapScrew.Solid() {
    var d = self.head_d;
    var h = self.head_h;
    var d_num = d / (1 mm);
    var h_num = h / (1 mm);
    var md_num = self.major_d / (1 mm);
    var c_num = (h_num * h_num + md_num * md_num / 4 - d_num * d_num / 4) / (2 * h_num);
    var R_num = Sqrt(c_num * c_num + d_num * d_num / 4);
    var R = R_num * 1 mm;
    var c = c_num * 1 mm;
    var sphere = Sphere(R).Translate(0 mm, 0 mm, c);
    var clip = Cylinder(h, d / 2, d / 2);
    var dome = sphere ^ clip;
    var sock_depth = h * 0.7;
    var sock_cr = self.socket / (2 * Cos(30 deg));
    var socket = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * sock_cr, Sin(i * 60 deg) * sock_cr);
    }).Extrude(sock_depth + 1 mm)
        .Translate(0 mm, 0 mm, -1 mm);
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, h);
    return (dome - socket) + shaft;
}

# ---------------------------------------------------------------------------
# CountersunkScrew — ISO 10642
#
# Conical head (flat top flush with surface) with hex socket, threaded shaft.
# Wide base at Z=0, narrows to shaft diameter at Z=head_h, shaft extends upward.
# ---------------------------------------------------------------------------

struct CountersunkScrew {
    Thread thread;
    Length major_d;
    Length head_d;
    Length head_h;
    Length socket;
    Length length;
}

# Creates an ISO 10642 countersunk screw.
CountersunkScrew CountersunkScrew(String size, Length length) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    return CountersunkScrew {
        thread: t,
        major_d: t.major_diameter,
        head_d: row[10] * 1 mm,
        head_h: row[11] * 1 mm,
        socket: row[12] * 1 mm,
        length: length
    };
}

# Renders the countersunk screw as a solid.
Solid CountersunkScrew.Solid() {
    var head = Cylinder(self.head_h, self.head_d / 2, self.major_d / 2);
    var sock_depth = self.head_h * 0.7;
    var sock_cr = self.socket / (2 * Cos(30 deg));
    var socket = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * sock_cr, Sin(i * 60 deg) * sock_cr);
    }).Extrude(sock_depth + 1 mm)
        .Translate(0 mm, 0 mm, -1 mm);
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, self.head_h);
    return (head - socket) + shaft;
}

# ---------------------------------------------------------------------------
# SetScrew — ISO 4026 (flat point)
#
# Fully threaded cylinder with hex socket recess on top.
# Bottom at Z=0, body extends upward (+Z).
# ---------------------------------------------------------------------------

struct SetScrew {
    Thread thread;
    Length major_d;
    Length socket;
    Length length;
}

# Creates an ISO 4026 set screw.
SetScrew SetScrew(String size, Length length) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    return SetScrew {
        thread: t,
        major_d: t.major_diameter,
        socket: row[13] * 1 mm,
        length: length
    };
}

# Renders the set screw as a solid.
Solid SetScrew.Solid() {
    var body = self.thread.Outside(self.length);
    var sock_depth = self.major_d * 0.6;
    var sock_cr = self.socket / (2 * Cos(30 deg));
    var socket = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * sock_cr, Sin(i * 60 deg) * sock_cr);
    }).Extrude(sock_depth + 1 mm)
        .Translate(0 mm, 0 mm, -1 mm);
    return body - socket;
}

# ---------------------------------------------------------------------------
# Thumbscrew — knurled head + threaded shaft
#
# Head at Z=0, shaft extends upward (+Z).
# ---------------------------------------------------------------------------

struct Thumbscrew {
    Thread thread;
    Length length;
    Length head_h;
    Length head_r;
    Knurl knurl;
}

# Creates a thumbscrew with default head dimensions and knurling.
Thumbscrew Thumbscrew(String size, Length length) {
    var t = T.New(size);
    var d = t.major_diameter;
    return Thumbscrew {
        thread: t,
        length: length,
        head_h: d * 0.8,
        head_r: d * 1.2,
        knurl: K.Knurl(Number(d) * 6, 0.3 mm, 30 deg)
    };
}

# Creates a thumbscrew with custom head dimensions and knurling.
Thumbscrew Thumbscrew(String size, Length length, Length head_h, Length head_r, Knurl knurl) {
    return Thumbscrew {
        thread: T.New(size),
        length: length,
        head_h: head_h,
        head_r: head_r,
        knurl: knurl
    };
}

# Renders the thumbscrew as a solid.
Solid Thumbscrew.Solid() {
    var head = self.knurl.ApplyZ(Cylinder(self.head_h, self.head_r, self.head_r));
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, self.head_h);
    return head + shaft;
}

# ---------------------------------------------------------------------------
# FlatHeadScrew — ISO 1580 slotted pan head
#
# Pan head with a single straight slot across the top, threaded shaft above.
# Head at Z=0, shaft extends upward (+Z).
# ---------------------------------------------------------------------------

struct FlatHeadScrew {
    Thread thread;
    Length head_d;
    Length head_h;
    Length slot_w;
    Length length;
}

# Creates an ISO 1580 flat head (slotted) screw.
FlatHeadScrew FlatHeadScrew(String size, Length length) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    return FlatHeadScrew {
        thread: t,
        head_d: row[14] * 1 mm,
        head_h: row[15] * 1 mm,
        slot_w: row[16] * 1 mm,
        length: length
    };
}

# Renders the flat head screw as a solid.
Solid FlatHeadScrew.Solid() {
    var hd = self.head_d;
    var hh = self.head_h;
    var head = Cylinder(hh, hd / 2, hd / 2);
    var slot_depth = hh * 0.8;
    var slot = Cube(hd + 1 mm, self.slot_w, slot_depth + 1 mm)
        .Translate(0 mm, 0 mm, slot_depth / 2 - 0.5 mm);
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, hh);
    return (head - slot) + shaft;
}

# ---------------------------------------------------------------------------
# PhillipsScrew — ISO 7045 Phillips pan head
#
# Pan head with a cross-shaped (Phillips) recess, threaded shaft above.
# Head at Z=0, shaft extends upward (+Z).
# ---------------------------------------------------------------------------

struct PhillipsScrew {
    Thread thread;
    Length head_d;
    Length head_h;
    Length phillips_w;
    Length length;
}

# Creates an ISO 7045 Phillips screw.
PhillipsScrew PhillipsScrew(String size, Length length) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    return PhillipsScrew {
        thread: t,
        head_d: row[14] * 1 mm,
        head_h: row[15] * 1 mm,
        phillips_w: row[17] * 1 mm,
        length: length
    };
}

# Renders the Phillips screw as a solid.
Solid PhillipsScrew.Solid() {
    var hd = self.head_d;
    var hh = self.head_h;
    var pw = self.phillips_w;
    var head = Cylinder(hh, hd / 2, hd / 2);
    var recess_depth = hh * 0.8;
    var arm_len = pw * 1.2;
    var arm_w = pw * 0.25;
    var slot_a = Cube(arm_len, arm_w, recess_depth + 1 mm)
        .Translate(0 mm, 0 mm, recess_depth / 2 - 0.5 mm);
    var slot_b = Cube(arm_w, arm_len, recess_depth + 1 mm)
        .Translate(0 mm, 0 mm, recess_depth / 2 - 0.5 mm);
    var recess = slot_a + slot_b;
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, hh);
    return (head - recess) + shaft;
}

# ---------------------------------------------------------------------------
# Standoff — female-female hex standoff
#
# Hex body with internal threads on both ends.
# Body spans Z=0 upward (+Z).
# ---------------------------------------------------------------------------

struct Standoff {
    Thread thread;
    Length hex_af;
    Length major_d;
    Length length;
}

# Creates a female-female hex standoff.
Standoff Standoff(String size, Length length) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    return Standoff {
        thread: t,
        hex_af: row[1] * 1 mm,
        major_d: t.major_diameter,
        length: length
    };
}

# Renders the standoff as a solid.
Solid Standoff.Solid() {
    var cr = self.hex_af / (2 * Cos(30 deg));
    var body = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * cr, Sin(i * 60 deg) * cr);
    }).Extrude(self.length);
    var thread_depth = Min(self.major_d, self.length / 2);
    var top_thread = self.thread.Inside(thread_depth)
        .Translate(0 mm, 0 mm, self.length - thread_depth);
    var bot_thread = self.thread.Inside(thread_depth);
    return body - top_thread - bot_thread;
}

# ---------------------------------------------------------------------------
# MaleStandoff — male-female hex standoff
#
# Hex body with internal thread at bottom and external thread protruding above.
# Hex body spans Z=0 upward (+Z). Male thread extends above the body.
# ---------------------------------------------------------------------------

struct MaleStandoff {
    Thread thread;
    Length hex_af;
    Length major_d;
    Length length;
    Length thread_len;
}

# Creates a male-female hex standoff.
MaleStandoff MaleStandoff(String size, Length length, Length thread_len) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    return MaleStandoff {
        thread: t,
        hex_af: row[1] * 1 mm,
        major_d: t.major_diameter,
        length: length,
        thread_len: thread_len
    };
}

# Renders the male standoff as a solid.
Solid MaleStandoff.Solid() {
    var cr = self.hex_af / (2 * Cos(30 deg));
    var body = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * cr, Sin(i * 60 deg) * cr);
    }).Extrude(self.length);
    var thread_depth = Min(self.major_d, self.length / 2);
    var bot_thread = self.thread.Inside(thread_depth);
    var male_thread = self.thread.Outside(self.thread_len)
        .Translate(0 mm, 0 mm, self.length);
    return (body - bot_thread) + male_thread;
}

# ---------------------------------------------------------------------------
# Showcase — renders one of each fastener type side by side
# ---------------------------------------------------------------------------

Array Showcase(String size, Length shaft_len, Length standoff_len) {
    var t = T.New(size);
    var row = DimRow(t.major_diameter);
    var sp = row[1] * 1 mm * 2;
    return [
        HexNut(size).Solid(),
        CapNut(size).Solid().Translate(sp, 0 mm, 0 mm),
        WingNut(size).Solid().Translate(sp * 2, 0 mm, 0 mm),
        Washer(size).Solid().Translate(sp * 3, 0 mm, 0 mm),
        HexBolt(size, shaft_len).Solid().Translate(sp * 4, 0 mm, 0 mm),
        SocketHeadCapScrew(size, shaft_len).Solid().Translate(sp * 5, 0 mm, 0 mm),
        ButtonHeadCapScrew(size, shaft_len).Solid().Translate(sp * 6, 0 mm, 0 mm),
        CountersunkScrew(size, shaft_len).Solid().Translate(sp * 7, 0 mm, 0 mm),
        SetScrew(size, shaft_len).Solid().Translate(sp * 8, 0 mm, 0 mm),
        Thumbscrew(size, shaft_len).Solid().Translate(sp * 9, 0 mm, 0 mm),
        FlatHeadScrew(size, shaft_len).Solid().Translate(sp * 10, 0 mm, 0 mm),
        PhillipsScrew(size, shaft_len).Solid().Translate(sp * 11, 0 mm, 0 mm),
        Standoff(size, standoff_len).Solid().Translate(sp * 12, 0 mm, 0 mm),
        MaleStandoff(size, standoff_len, shaft_len).Solid().Translate(sp * 13, 0 mm, 0 mm)
    ];
}
