# Metric Fastener Library
#
# Generates ISO metric fasteners: hex nuts, hex bolts, socket head cap screws,
# button head cap screws, countersunk screws, set screws, thumbscrews,
# flat head (slotted) screws, Phillips screws, and standoffs.
#
# Each fastener type is its own struct with a `Solid()` method.
# Dimensions are looked up from a shared ISO table by diameter.
#
# Usage:
#   var F = lib "github.com/firstlayer-xyz/facetlibs/fasteners@main";
#   return F.HexBolt("m8", 30 mm).Solid();

var T = lib "github.com/firstlayer-xyz/facetlibs/threads@main";
var K = lib "github.com/firstlayer-xyz/facetlibs/knurling@main";

# Re-export Knurl constructor so users can create knurl specs without
# importing knurling separately.
Knurl Knurl(Number count, Length depth, Angle pitch_angle) {
    return K.Knurl(count, depth, pitch_angle);
}

# ---------------------------------------------------------------------------
# ISO Metric Dimension Table
#
# Columns:
#   0: diameter     1: hex_af       2: nut_h        3: bolt_head_h
#   4: shcs_head_d  5: shcs_head_h  6: shcs_socket
#   7: bhcs_head_d  8: bhcs_head_h  9: bhcs_socket
#  10: fhcs_head_d 11: fhcs_head_h 12: fhcs_socket
#  13: set_socket
#  14: pan_head_d  15: pan_head_h
#  16: slot_w      17: phillips_w
# ---------------------------------------------------------------------------

var METRIC = [
    [ 2,    4.0,  1.6,  1.4,  3.8,   2.0,   1.5,  3.8,   1.3,   1.3,  3.8,    1.2,   1.3,  0.9,   4.0,   1.3,  0.5,  1.4  ],
    [ 2.5,  5.0,  2.0,  1.7,  4.5,   2.5,   2.0,  4.7,   1.5,   1.5,  4.7,    1.5,   1.5,  1.3,   5.0,   1.7,  0.6,  1.8  ],
    [ 3,    5.5,  2.4,  2.0,  5.5,   3.0,   2.5,  5.7,   1.65,  2.0,  5.54,   1.86,  2.0,  1.5,   6.0,   2.0,  0.8,  2.1  ],
    [ 4,    7.0,  3.2,  2.8,  7.0,   4.0,   3.0,  7.6,   2.2,   2.5,  7.53,   2.48,  2.5,  2.0,   8.0,   2.6,  1.0,  2.6  ],
    [ 5,    8.0,  4.7,  3.5,  8.5,   5.0,   4.0,  9.5,   2.75,  3.0,  9.43,   3.1,   3.0,  2.5,  10.0,   3.3,  1.2,  3.3  ],
    [ 6,   10.0,  5.2,  4.0, 10.0,   6.0,   5.0, 10.5,   3.3,   4.0, 11.34,   3.72,  4.0,  3.0,  12.0,   3.9,  1.6,  4.1  ],
    [ 8,   13.0,  6.8,  5.3, 13.0,   8.0,   6.0, 14.0,   4.4,   5.0, 15.24,   4.96,  5.0,  4.0,  16.0,   5.0,  2.0,  5.1  ],
    [10,   16.0,  8.4,  6.4, 16.0,  10.0,   8.0, 17.5,   5.5,   6.0, 19.22,   6.2,   6.0,  5.0,  20.0,   6.0,  2.5,  6.1  ],
    [12,   18.0, 10.8,  7.5, 18.0,  12.0,  10.0, 21.0,   6.6,   8.0, 23.12,   7.44,  8.0,  6.0,  24.0,   7.0,  3.0,  7.1  ],
    [16,   24.0, 14.8, 10.0, 24.0,  16.0,  14.0, 28.0,   8.8,  10.0, 29.01,   8.8,  10.0,  8.0,  30.0,   8.8,  4.0,  0    ],
    [20,   30.0, 18.0, 12.5, 30.0,  20.0,  17.0,  0,     0,     0,   36.05,  10.16, 12.0, 10.0,  36.0,  10.0,  5.0,  0    ],
    [24,   36.0, 21.5, 15.0, 36.0,  24.0,  18.0,  0,     0,     0,   39.0,   14.0,  14.0, 12.0,  44.0,  12.0,  6.0,  0    ],
    [30,   46.0, 25.6, 19.0, 45.0,  30.0,  22.0,  0,     0,     0,    0,      0,     0,   15.0,   0,     0,    0,    0    ],
    [36,   55.0, 31.0, 23.0, 54.0,  36.0,  27.0,  0,     0,     0,    0,      0,     0,   18.0,   0,     0,    0,    0    ],
    [42,   65.0, 34.0, 26.0, 63.0,  42.0,  32.0,  0,     0,     0,    0,      0,     0,   21.0,   0,     0,    0,    0    ],
    [48,   75.0, 38.0, 30.0, 72.0,  48.0,  36.0,  0,     0,     0,    0,      0,     0,   24.0,   0,     0,    0,    0    ],
    [56,   85.0, 45.0, 35.0, 84.0,  56.0,  41.0,  0,     0,     0,    0,      0,     0,   28.0,   0,     0,    0,    0    ],
    [64,   95.0, 51.0, 40.0, 96.0,  64.0,  46.0,  0,     0,     0,    0,      0,     0,   32.0,   0,     0,    0,    0    ]
];

# Looks up a row in the METRIC table by diameter.
Array MetricRow(Length d) {
    var v = Number(d);
    var matches = for i [0:<Size(METRIC)] {
        if METRIC[i][0] == v {
            yield METRIC[i];
        };
    };
    assert Size(matches) > 0, "unsupported metric fastener diameter";
    return matches[0];
}

# ---------------------------------------------------------------------------
# HexNut — ISO 4032 hex nut
#
# Hex prism body minus internal thread.
# Centered at origin, body from Z=0 upward (+Z).
# ---------------------------------------------------------------------------

struct HexNut {
    Thread thread;
    Length hex_af;
    Length nut_h;
}

# Creates an ISO 4032 hex nut.
HexNut HexNut(String size) {
    var t = T.New(size);
    var row = MetricRow(t.major_diameter);
    return HexNut {
        thread: t,
        hex_af: row[1] * 1 mm,
        nut_h: row[2] * 1 mm
    };
}

# Renders the hex nut as a solid.
Solid HexNut.Solid() {
    var cr = self.hex_af / (2 * Cos(30 deg));
    var hex = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * cr, Sin(i * 60 deg) * cr);
    }).Extrude(self.nut_h);
    var internal = self.thread.Inside(self.nut_h);
    return hex - internal;
}

# ---------------------------------------------------------------------------
# HexBolt — ISO 4014 hex bolt
#
# Head bottom at Z=0, head extends upward (+Z), shaft extends above head.
# ---------------------------------------------------------------------------

struct HexBolt {
    Thread thread;
    Length hex_af;
    Length head_h;
    Length length;
}

# Creates an ISO 4014 hex bolt with the given shaft length.
HexBolt HexBolt(String size, Length length) {
    var t = T.New(size);
    var row = MetricRow(t.major_diameter);
    return HexBolt {
        thread: t,
        hex_af: row[1] * 1 mm,
        head_h: row[3] * 1 mm,
        length: length
    };
}

# Renders the hex bolt as a solid.
Solid HexBolt.Solid() {
    var cr = self.hex_af / (2 * Cos(30 deg));
    var head = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * cr, Sin(i * 60 deg) * cr);
    }).Extrude(self.head_h);
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, self.head_h);
    return head + shaft;
}

# ---------------------------------------------------------------------------
# SocketHeadCapScrew — ISO 4762
#
# Cylindrical head with hex socket recess, threaded shaft above.
# Head at Z=0, shaft extends upward (+Z).
# ---------------------------------------------------------------------------

struct SocketHeadCapScrew {
    Thread thread;
    Length head_d;
    Length head_h;
    Length socket;
    Length length;
}

# Creates an ISO 4762 socket head cap screw.
SocketHeadCapScrew SocketHeadCapScrew(String size, Length length) {
    var t = T.New(size);
    var row = MetricRow(t.major_diameter);
    return SocketHeadCapScrew {
        thread: t,
        head_d: row[4] * 1 mm,
        head_h: row[5] * 1 mm,
        socket: row[6] * 1 mm,
        length: length
    };
}

# Renders the socket head cap screw as a solid.
Solid SocketHeadCapScrew.Solid() {
    var hh = self.head_h;
    var head = Cylinder(hh, self.head_d / 2, self.head_d / 2);
    var sock_depth = hh * 0.8;
    var sock_cr = self.socket / (2 * Cos(30 deg));
    var socket = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * sock_cr, Sin(i * 60 deg) * sock_cr);
    }).Extrude(sock_depth + 1 mm)
        .Translate(0 mm, 0 mm, -1 mm);
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, hh);
    return (head - socket) + shaft;
}

# ---------------------------------------------------------------------------
# ButtonHeadCapScrew — ISO 7380
#
# Low-profile dome head with hex socket, threaded shaft above.
# Head at Z=0, shaft extends upward (+Z).
# ---------------------------------------------------------------------------

struct ButtonHeadCapScrew {
    Thread thread;
    Length major_d;
    Length head_d;
    Length head_h;
    Length socket;
    Length length;
}

# Creates an ISO 7380 button head cap screw.
ButtonHeadCapScrew ButtonHeadCapScrew(String size, Length length) {
    var t = T.New(size);
    var row = MetricRow(t.major_diameter);
    return ButtonHeadCapScrew {
        thread: t,
        major_d: t.major_diameter,
        head_d: row[7] * 1 mm,
        head_h: row[8] * 1 mm,
        socket: row[9] * 1 mm,
        length: length
    };
}

# Renders the button head cap screw as a solid.
Solid ButtonHeadCapScrew.Solid() {
    var d = self.head_d;
    var h = self.head_h;
    var d_num = d / (1 mm);
    var h_num = h / (1 mm);
    var md_num = self.major_d / (1 mm);
    var c_num = (h_num * h_num + md_num * md_num / 4 - d_num * d_num / 4) / (2 * h_num);
    var R_num = Sqrt(c_num * c_num + d_num * d_num / 4);
    var R = R_num * 1 mm;
    var c = c_num * 1 mm;
    var sphere = Sphere(R).Translate(0 mm, 0 mm, c);
    var clip = Cylinder(h, d / 2, d / 2);
    var dome = sphere ^ clip;
    var sock_depth = h * 0.7;
    var sock_cr = self.socket / (2 * Cos(30 deg));
    var socket = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * sock_cr, Sin(i * 60 deg) * sock_cr);
    }).Extrude(sock_depth + 1 mm)
        .Translate(0 mm, 0 mm, -1 mm);
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, h);
    return (dome - socket) + shaft;
}

# ---------------------------------------------------------------------------
# CountersunkScrew — ISO 10642
#
# Conical head (flat top flush with surface) with hex socket, threaded shaft.
# Wide base at Z=0, narrows to shaft diameter at Z=head_h, shaft extends upward.
# ---------------------------------------------------------------------------

struct CountersunkScrew {
    Thread thread;
    Length major_d;
    Length head_d;
    Length head_h;
    Length socket;
    Length length;
}

# Creates an ISO 10642 countersunk screw.
CountersunkScrew CountersunkScrew(String size, Length length) {
    var t = T.New(size);
    var row = MetricRow(t.major_diameter);
    return CountersunkScrew {
        thread: t,
        major_d: t.major_diameter,
        head_d: row[10] * 1 mm,
        head_h: row[11] * 1 mm,
        socket: row[12] * 1 mm,
        length: length
    };
}

# Renders the countersunk screw as a solid.
Solid CountersunkScrew.Solid() {
    var head = Cylinder(self.head_h, self.head_d / 2, self.major_d / 2);
    var sock_depth = self.head_h * 0.7;
    var sock_cr = self.socket / (2 * Cos(30 deg));
    var socket = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * sock_cr, Sin(i * 60 deg) * sock_cr);
    }).Extrude(sock_depth + 1 mm)
        .Translate(0 mm, 0 mm, -1 mm);
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, self.head_h);
    return (head - socket) + shaft;
}

# ---------------------------------------------------------------------------
# SetScrew — ISO 4026 (flat point)
#
# Fully threaded cylinder with hex socket recess on top.
# Bottom at Z=0, body extends upward (+Z).
# ---------------------------------------------------------------------------

struct SetScrew {
    Thread thread;
    Length major_d;
    Length socket;
    Length length;
}

# Creates an ISO 4026 set screw.
SetScrew SetScrew(String size, Length length) {
    var t = T.New(size);
    var row = MetricRow(t.major_diameter);
    return SetScrew {
        thread: t,
        major_d: t.major_diameter,
        socket: row[13] * 1 mm,
        length: length
    };
}

# Renders the set screw as a solid.
Solid SetScrew.Solid() {
    var body = self.thread.Outside(self.length);
    var sock_depth = self.major_d * 0.6;
    var sock_cr = self.socket / (2 * Cos(30 deg));
    var socket = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * sock_cr, Sin(i * 60 deg) * sock_cr);
    }).Extrude(sock_depth + 1 mm)
        .Translate(0 mm, 0 mm, self.length - sock_depth);
    return body - socket;
}

# ---------------------------------------------------------------------------
# Thumbscrew — knurled head + threaded shaft
#
# Head at Z=0, shaft extends upward (+Z).
# ---------------------------------------------------------------------------

struct Thumbscrew {
    Thread thread;
    Length length;
    Length head_h;
    Length head_r;
    Knurl knurl;
}

# Creates a thumbscrew with default head dimensions and knurling.
Thumbscrew Thumbscrew(String size, Length length) {
    var t = T.New(size);
    var d = t.major_diameter;
    return Thumbscrew {
        thread: t,
        length: length,
        head_h: d * 0.8,
        head_r: d * 1.2,
        knurl: K.Knurl(Number(d) * 6, 0.3 mm, 30 deg)
    };
}

# Creates a thumbscrew with custom head dimensions and knurling.
Thumbscrew Thumbscrew(String size, Length length, Length head_h, Length head_r, Knurl knurl) {
    return Thumbscrew {
        thread: T.New(size),
        length: length,
        head_h: head_h,
        head_r: head_r,
        knurl: knurl
    };
}

# Renders the thumbscrew as a solid.
Solid Thumbscrew.Solid() {
    var head = self.knurl.ApplyZ(Cylinder(self.head_h, self.head_r, self.head_r));
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, self.head_h);
    return head + shaft;
}

# ---------------------------------------------------------------------------
# FlatHeadScrew — ISO 1580 slotted pan head
#
# Pan head with a single straight slot across the top, threaded shaft above.
# Head at Z=0, shaft extends upward (+Z).
# ---------------------------------------------------------------------------

struct FlatHeadScrew {
    Thread thread;
    Length head_d;
    Length head_h;
    Length slot_w;
    Length length;
}

# Creates an ISO 1580 flat head (slotted) screw.
FlatHeadScrew FlatHeadScrew(String size, Length length) {
    var t = T.New(size);
    var row = MetricRow(t.major_diameter);
    return FlatHeadScrew {
        thread: t,
        head_d: row[14] * 1 mm,
        head_h: row[15] * 1 mm,
        slot_w: row[16] * 1 mm,
        length: length
    };
}

# Renders the flat head screw as a solid.
Solid FlatHeadScrew.Solid() {
    var hd = self.head_d;
    var hh = self.head_h;
    var head = Cylinder(hh, hd / 2, hd / 2);
    var slot_depth = hh * 0.8;
    var slot = Cube(hd + 1 mm, self.slot_w, slot_depth + 1 mm)
        .Translate(0 mm, 0 mm, slot_depth / 2 - 0.5 mm);
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, hh);
    return (head - slot) + shaft;
}

# ---------------------------------------------------------------------------
# PhillipsScrew — ISO 7045 Phillips pan head
#
# Pan head with a cross-shaped (Phillips) recess, threaded shaft above.
# Head at Z=0, shaft extends upward (+Z).
# ---------------------------------------------------------------------------

struct PhillipsScrew {
    Thread thread;
    Length head_d;
    Length head_h;
    Length phillips_w;
    Length length;
}

# Creates an ISO 7045 Phillips screw.
PhillipsScrew PhillipsScrew(String size, Length length) {
    var t = T.New(size);
    var row = MetricRow(t.major_diameter);
    return PhillipsScrew {
        thread: t,
        head_d: row[14] * 1 mm,
        head_h: row[15] * 1 mm,
        phillips_w: row[17] * 1 mm,
        length: length
    };
}

# Renders the Phillips screw as a solid.
Solid PhillipsScrew.Solid() {
    var hd = self.head_d;
    var hh = self.head_h;
    var pw = self.phillips_w;
    var head = Cylinder(hh, hd / 2, hd / 2);
    var recess_depth = hh * 0.8;
    var arm_len = pw * 1.2;
    var arm_w = pw * 0.25;
    var slot_a = Cube(arm_len, arm_w, recess_depth + 1 mm)
        .Translate(0 mm, 0 mm, recess_depth / 2 - 0.5 mm);
    var slot_b = Cube(arm_w, arm_len, recess_depth + 1 mm)
        .Translate(0 mm, 0 mm, recess_depth / 2 - 0.5 mm);
    var recess = slot_a + slot_b;
    var shaft = self.thread.Outside(self.length)
        .Translate(0 mm, 0 mm, hh);
    return (head - recess) + shaft;
}

# ---------------------------------------------------------------------------
# Standoff — female-female hex standoff
#
# Hex body with internal threads on both ends.
# Body spans Z=0 upward (+Z).
# ---------------------------------------------------------------------------

struct Standoff {
    Thread thread;
    Length hex_af;
    Length major_d;
    Length length;
}

# Creates a female-female hex standoff.
Standoff Standoff(String size, Length length) {
    var t = T.New(size);
    var row = MetricRow(t.major_diameter);
    return Standoff {
        thread: t,
        hex_af: row[1] * 1 mm,
        major_d: t.major_diameter,
        length: length
    };
}

# Renders the standoff as a solid.
Solid Standoff.Solid() {
    var cr = self.hex_af / (2 * Cos(30 deg));
    var body = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * cr, Sin(i * 60 deg) * cr);
    }).Extrude(self.length);
    var thread_depth = Min(self.major_d, self.length / 2);
    var top_thread = self.thread.Inside(thread_depth)
        .Translate(0 mm, 0 mm, self.length - thread_depth);
    var bot_thread = self.thread.Inside(thread_depth);
    return body - top_thread - bot_thread;
}

# ---------------------------------------------------------------------------
# MaleStandoff — male-female hex standoff
#
# Hex body with internal thread at bottom and external thread protruding above.
# Hex body spans Z=0 upward (+Z). Male thread extends above the body.
# ---------------------------------------------------------------------------

struct MaleStandoff {
    Thread thread;
    Length hex_af;
    Length major_d;
    Length length;
    Length thread_len;
}

# Creates a male-female hex standoff.
MaleStandoff MaleStandoff(String size, Length length, Length thread_len) {
    var t = T.New(size);
    var row = MetricRow(t.major_diameter);
    return MaleStandoff {
        thread: t,
        hex_af: row[1] * 1 mm,
        major_d: t.major_diameter,
        length: length,
        thread_len: thread_len
    };
}

# Renders the male standoff as a solid.
Solid MaleStandoff.Solid() {
    var cr = self.hex_af / (2 * Cos(30 deg));
    var body = Polygon(for i [0:<6] {
        yield Point2d(Cos(i * 60 deg) * cr, Sin(i * 60 deg) * cr);
    }).Extrude(self.length);
    var thread_depth = Min(self.major_d, self.length / 2);
    var bot_thread = self.thread.Inside(thread_depth);
    var male_thread = self.thread.Outside(self.thread_len)
        .Translate(0 mm, 0 mm, self.length);
    return (body - bot_thread) + male_thread;
}

# ---------------------------------------------------------------------------
# Showcase — renders one of each fastener type side by side
# ---------------------------------------------------------------------------

Array Showcase(String size, Length shaft_len, Length standoff_len) {
    var t = T.New(size);
    var row = MetricRow(t.major_diameter);
    var sp = row[1] * 1 mm * 2;
    return [
        HexNut(size).Solid(),
        HexBolt(size, shaft_len).Solid().Translate(sp, 0 mm, 0 mm),
        SocketHeadCapScrew(size, shaft_len).Solid().Translate(sp * 2, 0 mm, 0 mm),
        ButtonHeadCapScrew(size, shaft_len).Solid().Translate(sp * 3, 0 mm, 0 mm),
        CountersunkScrew(size, shaft_len).Solid().Translate(sp * 4, 0 mm, 0 mm),
        SetScrew(size, shaft_len).Solid().Translate(sp * 5, 0 mm, 0 mm),
        Thumbscrew(size, shaft_len).Solid().Translate(sp * 6, 0 mm, 0 mm),
        FlatHeadScrew(size, shaft_len).Solid().Translate(sp * 7, 0 mm, 0 mm),
        PhillipsScrew(size, shaft_len).Solid().Translate(sp * 8, 0 mm, 0 mm),
        Standoff(size, standoff_len).Solid().Translate(sp * 9, 0 mm, 0 mm),
        MaleStandoff(size, standoff_len, shaft_len).Solid().Translate(sp * 10, 0 mm, 0 mm)
    ];
}
